# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_gcs("info-4940-models", prefix = "ire2/")
v <- vetiver_pin_read(b, "gss-rf-model", version = "20241208T044733Z-d76b6")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
